export const data = [
  {
    id: '1',
    name: 'Amanda',
    sub: '9-7-5 for time',
    desc1: 'muscle ups',
    desc2: 'squat snatches 135/95 lb',
    desc3: '',
    desc4: '',
    desc5: '',
  },
  {
    id: '2',
    name: 'Angie',
    sub: 'for time',
    desc1: '100 pull ups',
    desc2: '100 push ups',
    desc3: '100 sit ups',
    desc4: '100 squats',
    desc5: '',
  },
  {
    id: '3',
    name: 'Annie',
    sub: '50-40-30-20-10 for time',
    desc1: 'double unders',
    desc2: 'sit ups',
    desc3: '',
    desc4: '',
    desc5: '',
  },
  {
    id: '4',
    name: '',
    sub: '',
    desc1: '',
    desc2: '',
    desc3: '',
    desc4: '',
    desc5: '',
  },
]
