export const data = [
  {
    // 1
    name: 'Amanda',
    sub: '9-7-5 for time',
    desc1: 'muscle ups',
    desc2: 'squat snatches 135/95 lb',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '14 mins',
  },
  {
    // 2
    name: 'Angie',
    sub: 'for time',
    desc1: '100 pull ups',
    desc2: '100 push ups',
    desc3: '100 sit ups',
    desc4: '100 squats',
    desc5: '',
    desc6: '',
    target: '28 mins',
  },
  {
    // 3
    name: 'Annie',
    sub: '50-40-30-20-10 for time',
    desc1: 'double unders',
    desc2: 'sit ups',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '11 mins',
  },
  {
    // 4
    name: 'Barbara',
    sub: '5 rounds for time',
    desc1: '20 pulls ups',
    desc2: '30 push ups',
    desc3: '40 sit ups',
    desc4: '50 air squats',
    desc5: '3 mins rest',
    desc6: '',
    target: '8 mins per round',
  },
  {
    // 5
    name: 'Chelsea',
    sub: 'emom for 30 mins',
    desc1: '5 pull ups',
    desc2: '10 push ups',
    desc3: '15 air squats',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '20 rounds',
  },
  {
    // 6
    name: 'Cindy',
    sub: 'amrap in 20 minutes',
    desc1: '5 pull ups',
    desc2: '10 push ups',
    desc3: '15 air squats',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '12 rounds',
  },
  {
    // 7
    name: 'Diane',
    sub: '21-15-9 for time',
    desc1: 'deadlifts 225/155 lb',
    desc2: 'handstand push ups',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '10 mins',
  },
  {
    // 8
    name: 'Elizabeth',
    sub: '21-15-9 for time',
    desc1: 'squat cleans 135/95 lb',
    desc2: 'ring dips',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '14 mins',
  },
  {
    // 9
    name: 'Eva',
    sub: '5 rounds for time',
    desc1: '800m run',
    desc2: '30 KB swings, 2 poods',
    desc3: '30 pull ups',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '70 mins',
  },
  {
    // 10
    name: 'Fran',
    sub: '21-15-9 for time',
    desc1: 'thrusters 95/75 lb',
    desc2: 'pull ups',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '9 mins',
  },
  {
    // 11
    name: 'Grace',
    sub: '30 reps for time',
    desc1: 'clean & jerks 135/95 lb',
    desc2: '',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '8 mins',
  },
  {
    // 12
    name: 'Helen',
    sub: '3 rounds for time',
    desc1: '400m run',
    desc2: '21 KB swings 50/35 lb',
    desc3: '12 pull ups',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '16 mins',
  },
  {
    // 13
    name: 'Isabel',
    sub: '30 reps for time',
    desc1: 'snatches 135/95 lb',
    desc2: '',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '16 mins',
  },
  {
    // 14
    name: 'Jackie',
    sub: 'for time',
    desc1: '1000m row',
    desc2: '50 thrusters 45/35 lb',
    desc3: '30 pull ups',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '18 mins',
  },
  {
    // 15
    name: 'Karen',
    sub: 'for time',
    desc1: '150 wall ball shots 20/14 lb',
    desc2: '',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '15 mins',
  },
  {
    // 16
    name: 'Kelly',
    sub: '5 rounds for time',
    desc1: '400m run',
    desc2: '30 box jumps 24/20"',
    desc3: '30 wall ball shots 20/14 lb',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '50 mins',
  },
  {
    // 17
    name: 'Linda',
    sub: '10-9-8-7-6-5-4-3-2-1 for time',
    desc1: 'deadlifts 1.5 bodyweight',
    desc2: 'bench presses bodyweight',
    desc3: 'cleans 0.75 bodyweight',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '30 mins',
  },
  {
    // 18
    name: 'Lynne',
    sub: '5 rounds for max reps',
    desc1: 'bench presses bodyweight',
    desc2: 'pull ups',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '20 mins',
  },
  {
    // 19
    name: 'Mary',
    sub: 'amrap in 20 mins',
    desc1: '5 handstand push ups',
    desc2: '10 alternating pistols',
    desc3: '15 pull ups',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '5 rounds',
  },
  {
    // 20
    name: 'Nancy',
    sub: '5 rounds for time',
    desc1: '400m rum',
    desc2: '15 OH squats 95/65 lb',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '22 mins',
  },
  {
    // 21
    name: 'Nicole',
    sub: 'amrap in 20 mins',
    desc1: '400m run',
    desc2: 'max reps pull ups',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '55 reps',
  },
  {
    // 22
    name: 'Candy',
    sub: '5 rounds for time',
    desc1: '20 pull ups',
    desc2: '40 push ups',
    desc3: '60 air squats',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '38 mins',
  },
  {
    // 23
    name: 'Gwen',
    sub: '15-12-9 for load',
    desc1: 'clean & jerks touch & go',
    desc2: 'rest as needed between sets',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '390 lbs',
  },
  {
    // 24
    name: 'Hope',
    sub: '3 rounds',
    desc1: '1 min burpees',
    desc2: '1 min power snatches 75/55 lb',
    desc3: '1 min box jumps 24/20"',
    desc4: '1 min thrusters 75/55 lb',
    desc5: '1 min C2B pull ups',
    desc6: '1 min rest',
    target: '150 reps',
  },
  {
    // 25
    name: 'Maggie',
    sub: '5 rounds for time',
    desc1: '20 handstand push ups',
    desc2: '40 pull ups',
    desc3: '60 alternating pistols',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '60 mins',
  },
  {
    // 26
    name: 'Marguerita',
    sub: '50 rounds for time',
    desc1: '1 burpee',
    desc2: '1 push up',
    desc3: '1 jumping jack',
    desc4: '1 sit up',
    desc5: '1 handstand',
    desc6: '',
    target: '25 mins',
  },
  {
    // 27
    name: 'Megan',
    sub: '21-15-9 for time',
    desc1: 'burpees',
    desc2: 'KB swings 53/35 lb',
    desc3: 'double unders',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '8 mins',
  },
  {
    // 28
    name: 'Grettel',
    sub: '10 rounds for time',
    desc1: '3 clean & jerks 135/95 lb',
    desc2: '3 burpees over the bar',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '6 mins',
  },
  {
    // 29
    name: 'Ingrid',
    sub: '10 rounds for time',
    desc1: '3 snatches 135/95 lb',
    desc2: '3 burpees over the bar',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '10 mins',
  },
  {
    // 30
    name: 'Barbara Ann',
    sub: '5 rounds for time',
    desc1: '20 handstand push ups',
    desc2: '30 deadlifts 135/95 lb',
    desc3: '40 sit ups',
    desc4: '50 double unders',
    desc5: '3 mins rest',
    desc6: '',
    target: '',
  },
  {
    // 31
    name: 'Lyla',
    sub: '10-9-8-7-6-5-4-3-2-1 for time',
    desc1: 'muscle ups',
    desc2: 'clean & jerks bodyweight',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '',
  },
  {
    // 32
    name: 'Ellen',
    sub: '3 rounds for time',
    desc1: '20 burpees',
    desc2: '21 single DB snatches 50/35 lb',
    desc3: '12 double DB thrusters 50/35 lb',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '',
  },
  {
    // 33
    name: 'Andi',
    sub: 'for time',
    desc1: '100 hang power snatches 65/45 lb',
    desc2: '100 push presses 65/45 lb',
    desc3: '100 sumo deadlift high pulls 65/45 lb',
    desc4: '100 front squats 65/45 lb',
    desc5: '',
    desc6: '',
    target: '',
  },
  {
    // 34
    name: 'Lane',
    sub: '5 rounds of max reps',
    desc1: 'hang power snatches 0.75 bodyweight ',
    desc2: 'handstand push ups',
    desc3: 'rest as needed between rounds',
    desc4: '',
    desc5: '',
    desc6: '',
    target: '',
  },
]
