export const data = [
  {
    // 1
    name: 'JT',
    sub: '21-15-9 for time',
    desc1: 'handstand push ups',
    desc2: 'ring dips',
    desc3: 'push ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'In honor of Petty Officer 1st Class Jeff Taylor, 30, of Midway, West Virginia, who was killed on 28 June 2005, while conducting combat operations in the vicinity of Asadabad, Afghanistan, in Kumar Province.',
  },
  {
    // 2
    name: 'Michael',
    sub: '3 rounds for time',
    desc1: '800m run',
    desc2: '50 back extensions',
    desc3: '50 sit ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'In honor of Navy Lieutenant Michael McGreevy, 30, of Portville, NY, who was killed in Afghanistan 28 June 2005',
  },
  {
    // 3
    name: 'Murph',
    sub: 'for time',
    desc1: '1 mile run',
    desc2: '100 pull ups',
    desc3: '200 push ups',
    desc4: '300 squats',
    desc5: '1 mile run',
    desc6: 'partition pull ups, push ups and squats as needed',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'In memory of Navy Lieutenant Michael Murphy, 29, of Patchogue, N.Y., who was killed in Afghanistan on 28 June 2005.',
  },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
]
