export const data = [
  {
    // 1
    name: 'JT',
    sub: '21-15-9 for time',
    desc1: 'handstand push ups',
    desc2: 'ring dips',
    desc3: 'push ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Petty Officer 1st Class Jeff Taylor',
  },
  {
    // 2
    name: 'Michael',
    sub: '3 rounds for time',
    desc1: '800m run',
    desc2: '50 back extensions',
    desc3: '50 sit ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Navy Lieutenant Michael McGreevy',
  },
  {
    // 3
    name: 'Murph',
    sub: 'for time',
    desc1: '1 mile run',
    desc2: '100 pull ups',
    desc3: '200 push ups',
    desc4: '300 squats',
    desc5: '1 mile run',
    desc7: '(partition pull ups, push ups and squats as needed)',
    desc6: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Navy Lieutenant Michael Murphy',
  },
  {
    // 4
    name: 'Daniel',
    sub: 'for time',
    desc1: '50 pull ups',
    desc2: '400m run',
    desc3: '21 thrusters 95 lbs',
    desc4: '800m run',
    desc5: '21 thrusters 95 lbs',
    desc6: '400m run',
    desc7: '50 pull ups',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Army Sgt 1st Class Daniel Crabtree',
  },
  {
    // 5
    name: 'Josh',
    sub: 'for time',
    desc1: '21 overhead squats 95 lbs',
    desc2: '42 pull ups',
    desc3: '15 overhead squats 95 lbs',
    desc4: '30 pull ups',
    desc5: '9 overhead squats 95 lbs',
    desc6: '18 pull ups',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'US Army Staff Sgt. Joshua Hager',
  },
  {
    // 6
    name: 'Jason',
    sub: 'for time',
    desc1: '100 squats',
    desc2: '5 muscle ups',
    desc3: '75 squats',
    desc4: '10 muscle ups',
    desc5: '50 squats',
    desc6: '15 muscle ups',
    desc7: '25 squats',
    desc8: '20 muscle ups',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'S01 (SEAL) Jason Dale Lewis',
  },
  {
    // 7
    name: 'Badger',
    sub: '3 rounds for time',
    desc1: '30 squat cleans 95 lbs',
    desc2: '30 pull ups',
    desc3: '800m run',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'US Navy Chief Petty Officer Mark Carter',
  },
  {
    // 8
    name: 'Joshie',
    sub: '3 rounds for time',
    desc1: '21 DB snatches right arm 40 lbs',
    desc2: '21 L pull ups',
    desc3: '21 DB snatches left arm 40 lbs',
    desc4: '21 L pull ups',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Staff Sgt. Joshua Whitaker',
  },
  {
    // 9
    name: 'Nate',
    sub: '20 min amrap',
    desc1: '2 muscle ups',
    desc2: '4 handstand push ups',
    desc3: '8 2-pood KB swings',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Navy Chief Special Warfare Operator (SEAL) Nate Hardy',
  },
  {
    // 10
    name: 'Randy',
    sub: '75 reps for time',
    desc1: 'power snatch 75 lbs',
    desc2: '',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'LAPD veteran and SWAT team member Randy Simmons',
  },
  {
    // 11
    name: 'Tommy V',
    sub: 'for time',
    desc1: '21 thrusters 115 lbs',
    desc2: '12 rope climbs 15 ft',
    desc3: '15 thrusters 115 lbs',
    desc4: '9 rope climbs 15 ft',
    desc5: '9 thrusters 115 lbs',
    desc6: '6 rope climbs 15 ft',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Senior Chief Petty Officer Thomas J. Valentine',
  },
  {
    // 12
    name: 'Griff',
    sub: 'for time',
    desc1: '800m run',
    desc2: '400m run backwards',
    desc3: '800n run',
    desc4: '400m run backwards',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Air Force Staff Sgt. Travis L. Griffin',
  },
  {
    // 13
    name: 'Ryan',
    sub: '5 rounds for time',
    desc1: '7 muscle ups',
    desc2: '21 burpees',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Maplewood, Missouri firefighter Ryan Hummert',
  },
  {
    // 14
    name: 'Erin',
    sub: '5 rounds for time',
    desc1: '15 DB split cleans 40 lbs',
    desc2: '21 pull ups',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Canadian Army Master Cpl. Erin Doyle',
  },
  {
    // 15
    name: 'Mr Joshua',
    sub: '5 rounds for time',
    desc1: '400m run',
    desc2: '30 glute-ham sit ups',
    desc3: '15 DL 250 lbs',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Navy Special Warfare Operator 1st Class (SEAL) Joshua Thomas Harris',
  },
  {
    // 16
    name: 'DT',
    sub: '5 rounds for time',
    desc1: '12 DL 155 lbs',
    desc2: '9 hang power clean 155 lbs',
    desc3: '6 push jerks 155 lbs',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Air Force Staff Sgt. Timothy P. Davis',
  },
  {
    // 17
    name: 'Danny',
    sub: '20 min amrap',
    desc1: '30 box jumps 24"',
    desc2: '20 push press 115 lbs',
    desc3: '30 pull ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Oakland SWAT Sgt. Daniel Sakai',
  },
  {
    // 18
    name: 'Hansen',
    sub: '5 rounds for time',
    desc1: '30 2-pood KB swings',
    desc2: '30 burpees',
    desc3: '30 glute-ham sit ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Marine Staff Sgt. Daniel Hansen',
  },
  {
    // 19
    name: 'Tyler',
    sub: '5 rounds for time',
    desc1: '7 muscle ups',
    desc2: '21 sumo DL high pull 95 lbs',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army 1st Lt. Tyler E. Parten',
  },
  {
    // 20
    name: 'Lumberjack 20',
    sub: '',
    desc1: '20 DL 275 lbs',
    desc2: '400m run',
    desc3: '20 2-pood KB swings',
    desc4: '400m run',
    desc5: '20 overhead squats 115 lbs',
    desc6: '400m run',
    desc7: '20 burpees',
    desc8: '400m run',
    desc9: '20 C2B pull ups',
    desc10: '400m run',
    desc11: '20 box jumps 24"',
    desc12: '400m run',
    desc13: '20 DB squat cleans 45 lbs each',
    desc14: '400m run',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Spc. Frederick Greene, Pfc. Aaron Thomas Nemelka, Pfc. Michael Pearson, and Spc. Kham Xiong, along with 11 of the wounded who were active CrossFit athletes in the 20th Engineer Battalion, home to Lumberjack CrossFit',
  },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
]
