export const data = [
  {
    name: 'Amanda',
    sub: '9-7-5 for time',
    desc1: 'muscle ups',
    desc2: 'squat snatches 135/95 lb',
    desc3: '',
    desc4: '',
    desc5: '',
    target: '14 mins',
  },
  {
    name: 'Angie',
    sub: 'for time',
    desc1: '100 pull ups',
    desc2: '100 push ups',
    desc3: '100 sit ups',
    desc4: '100 squats',
    desc5: '',
    target: '28 mins',
  },
  {
    name: 'Annie',
    sub: '50-40-30-20-10 for time',
    desc1: 'double unders',
    desc2: 'sit ups',
    desc3: '',
    desc4: '',
    desc5: '',
    target: '11 mins',
  },
  {
    name: 'Barbara',
    sub: '5 rounds for time',
    desc1: '20 pulls ups',
    desc2: '30 push ups',
    desc3: '40 sit ups',
    desc4: '50 air squats',
    desc5: '3 mins rest',
    target: '8 mins per round',
  },
]
