export const data = [
  {
    // 1
    name: 'JT',
    sub: '21-15-9 for time',
    desc1: 'handstand push ups',
    desc2: 'ring dips',
    desc3: 'push ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Petty Officer 1st Class Jeff Taylor',
  },
  {
    // 2
    name: 'Michael',
    sub: '3 rounds for time',
    desc1: '800m run',
    desc2: '50 back extensions',
    desc3: '50 sit ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Navy Lieutenant Michael McGreevy',
  },
  {
    // 3
    name: 'Murph',
    sub: 'for time',
    desc1: '1 mile run',
    desc2: '100 pull ups',
    desc3: '200 push ups',
    desc4: '300 squats',
    desc5: '1 mile run',
    desc7: '(partition pull ups, push ups and squats as needed)',
    desc6: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Navy Lieutenant Michael Murphy',
  },
  {
    // 4
    name: 'Daniel',
    sub: 'for time',
    desc1: '50 pull ups',
    desc2: '400m run',
    desc3: '21 thrusters 95 lbs',
    desc4: '800m run',
    desc5: '21 thrusters 95 lbs',
    desc6: '400m run',
    desc7: '50 pull ups',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Army Sgt 1st Class Daniel Crabtree',
  },
  {
    // 5
    name: 'Josh',
    sub: 'for time',
    desc1: '21 overhead squats 95 lbs',
    desc2: '42 pull ups',
    desc3: '15 overhead squats 95 lbs',
    desc4: '30 pull ups',
    desc5: '9 overhead squats 95 lbs',
    desc6: '18 pull ups',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'US Army Staff Sgt. Joshua Hager',
  },
  {
    // 6
    name: 'Jason',
    sub: 'for time',
    desc1: '100 squats',
    desc2: '5 muscle ups',
    desc3: '75 squats',
    desc4: '10 muscle ups',
    desc5: '50 squats',
    desc6: '15 muscle ups',
    desc7: '25 squats',
    desc8: '20 muscle ups',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'S01 (SEAL) Jason Dale Lewis',
  },
  {
    // 7
    name: 'Badger',
    sub: '3 rounds for time',
    desc1: '30 squat cleans 95 lbs',
    desc2: '30 pull ups',
    desc3: '800m run',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'US Navy Chief Petty Officer Mark Carter',
  },
  {
    // 8
    name: 'Joshie',
    sub: '3 rounds for time',
    desc1: '21 DB snatches right arm 40 lbs',
    desc2: '21 L pull ups',
    desc3: '21 DB snatches left arm 40 lbs',
    desc4: '21 L pull ups',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Staff Sgt. Joshua Whitaker',
  },
  {
    // 9
    name: 'Nate',
    sub: '20 min amrap',
    desc1: '2 muscle ups',
    desc2: '4 handstand push ups',
    desc3: '8 KB swings 2 poods',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Navy Chief Special Warfare Operator (SEAL) Nate Hardy',
  },
  {
    // 10
    name: 'Randy',
    sub: '75 reps for time',
    desc1: 'power snatch 75 lbs',
    desc2: '',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'LAPD veteran and SWAT team member Randy Simmons',
  },
  {
    // 11
    name: 'Tommy V',
    sub: 'for time',
    desc1: '21 thrusters 115 lbs',
    desc2: '12 rope climbs 15 ft',
    desc3: '15 thrusters 115 lbs',
    desc4: '9 rope climbs 15 ft',
    desc5: '9 thrusters 115 lbs',
    desc6: '6 rope climbs 15 ft',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Senior Chief Petty Officer Thomas J. Valentine',
  },
  {
    // 12
    name: 'Griff',
    sub: 'for time',
    desc1: '800m run',
    desc2: '400m run backwards',
    desc3: '800n run',
    desc4: '400m run backwards',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Air Force Staff Sgt. Travis L. Griffin',
  },
  {
    // 13
    name: 'Ryan',
    sub: '5 rounds for time',
    desc1: '7 muscle ups',
    desc2: '21 burpees',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Maplewood, Missouri firefighter Ryan Hummert',
  },
  {
    // 14
    name: 'Erin',
    sub: '5 rounds for time',
    desc1: '15 DB split cleans 40 lbs',
    desc2: '21 pull ups',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Canadian Army Master Cpl. Erin Doyle',
  },
  {
    // 15
    name: 'Mr Joshua',
    sub: '5 rounds for time',
    desc1: '400m run',
    desc2: '30 glute-ham sit ups',
    desc3: '15 DL 250 lbs',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Navy Special Warfare Operator 1st Class (SEAL) Joshua Thomas Harris',
  },
  {
    // 16
    name: 'DT',
    sub: '5 rounds for time',
    desc1: '12 DL 155 lbs',
    desc2: '9 hang power clean 155 lbs',
    desc3: '6 push jerks 155 lbs',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Air Force Staff Sgt. Timothy P. Davis',
  },
  {
    // 17
    name: 'Danny',
    sub: '20 min amrap',
    desc1: '30 box jumps 24"',
    desc2: '20 push press 115 lbs',
    desc3: '30 pull ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Oakland SWAT Sgt. Daniel Sakai',
  },
  {
    // 18
    name: 'Hansen',
    sub: '5 rounds for time',
    desc1: '30 KB swings 2 poods',
    desc2: '30 burpees',
    desc3: '30 glute-ham sit ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Marine Staff Sgt. Daniel Hansen',
  },
  {
    // 19
    name: 'Tyler',
    sub: '5 rounds for time',
    desc1: '7 muscle ups',
    desc2: '21 sumo DL high pull 95 lbs',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army 1st Lt. Tyler E. Parten',
  },
  {
    // 20
    name: 'Lumberjack 20',
    sub: '',
    desc1: '20 DL 275 lbs',
    desc2: '400m run',
    desc3: '20 KB swings 2 poods',
    desc4: '400m run',
    desc5: '20 overhead squats 115 lbs',
    desc6: '400m run',
    desc7: '20 burpees',
    desc8: '400m run',
    desc9: '20 C2B pull ups',
    desc10: '400m run',
    desc11: '20 box jumps 24"',
    desc12: '400m run',
    desc13: '20 DB squat cleans 45 lbs each',
    desc14: '400m run',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Spc. Frederick Greene, Pfc. Aaron Thomas Nemelka, Pfc. Michael Pearson, and Spc. Kham Xiong, along with 11 of the wounded who were active CrossFit athletes in the 20th Engineer Battalion, home to Lumberjack CrossFit',
  },
  {
    // 21
    name: 'Stephen',
    sub: '30-25-20-15-10-5 for time',
    desc1: 'GHD sit ups',
    desc2: 'back extensions',
    desc3: 'knees to elbows',
    desc4: 'stiff legged DL 95 lbs',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Princess Patricia’s Canadian Light Infantry member Cpl. Stephen Bouzane',
  },
  {
    // 22
    name: 'Garrett',
    sub: '3 rounds for time',
    desc1: '75 squats',
    desc2: '25 ring handstand push ups',
    desc3: '25 L push ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Marine Capt. Garrett T. “Tubes” Lawton',
  },
  {
    // 23
    name: 'War Frank',
    sub: '3 rounds for time',
    desc1: '25 muscle ups',
    desc2: '100 squats',
    desc3: '35 GHD sit ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Marine Capt. Warren A. Frank',
  },
  {
    // 24
    name: 'McGhee',
    sub: '30 min amrap',
    desc1: '5 DL 275 lbs',
    desc2: '13 push ups',
    desc3: '9 box jumps 24"',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Cpl. Ryan C. McGhee',
  },
  {
    // 25
    name: 'Paul',
    sub: '5 rounds for time',
    desc1: '50 double unders',
    desc2: '35 knees to elbows',
    desc3: '30 yards overhead walk 185 lbs',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Pittsburgh Police Officer Paul John Rizzo Domenic Sciullo II',
  },
  {
    // 26
    name: 'Jerry',
    sub: 'for time',
    desc1: '1 mile run',
    desc2: '2km row',
    desc3: '1 mile run',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Sgt. Maj. Jerry Dwayne Patton',
  },
  {
    // 27
    name: 'Nutts',
    sub: 'for time',
    desc1: '10 handstand push ups',
    desc2: '15 DL 250 lbs',
    desc3: '25 box jumps 30"',
    desc4: '50 pull ups',
    desc5: "100 wall ball shots 20 lbs 10'",
    desc6: '200 double unders',
    desc7: '400m run with 45 lb plate',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Canadian Armed Forces Lt. Andrew Richard Nuttall,',
  },
  {
    // 28
    name: 'Arnie',
    sub: 'with a single KB for time 2 poods',
    desc1: '21 turkish get ups right arm',
    desc2: '50 swings',
    desc3: '21 overhead squats left arm',
    desc4: '50 swings',
    desc5: '21 overhead squats right arn',
    desc6: '50 swings',
    desc7: '21 turkish get ups left arm',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Los Angeles County Firefighter Specialist Arnaldo “Arnie” Quinones',
  },
  {
    // 29
    name: 'The Seven',
    sub: '7 rounds for time',
    desc1: '7 handstand push ups',
    desc2: '7 thrusters 135 lbs',
    desc3: '7 knees to elbows',
    desc4: '7 burpees',
    desc5: '7 KB swings 2 poods',
    desc6: '7 pull ups',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'CIA officers Jennifer Lynne Matthews, Scott Michael Roberson, Harold E. Brown Jr., Darren LaBonte, Elizabeth Hanson, and security contractors Jeremy Jason Wise, and Dane Clark Paresi',
  },
  {
    // 30
    name: 'RJ',
    sub: '5 rounds for time',
    desc1: '800m run',
    desc2: '5 rope climbs 15 ft',
    desc3: '50 push ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Veteran LAPD officer and U.S. Marine Corps Reservist Sgt. Maj. Robert J. Cottle',
  },
  {
    // 31
    name: 'Luce',
    sub: 'with 20 lb vest for time',
    desc1: '1km run',
    desc2: '10 muscle ups',
    desc3: '100 squats',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Captain Ronald G. Luce',
  },
  {
    // 32
    name: 'Johnson',
    sub: '20 min amrap',
    desc1: '9 DL 245 lbs',
    desc2: '8 muscle ups',
    desc3: '9 squat cleans 155 lbs',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Marine 1st Lt. Michael E. Johnson',
  },
  {
    // 33
    name: 'Roy',
    sub: '5 rounds for time',
    desc1: '15 DL 225 lbs',
    desc2: '20 box jumps 24"',
    desc3: '25 pull ups',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Marine Corps Sgt. Michael C. Roy',
  },
  {
    // 34
    name: 'Adambrown',
    sub: '2 rounds for time',
    desc1: '24 DL 295 lbs',
    desc2: '24 box jumps 24"',
    desc3: '24 wall ball shots 20 lbs',
    desc4: '24 bench presses 195 lbs',
    desc5: '24 box jumps 24"',
    desc6: '24 wall ball shots 20 lbs',
    desc7: '24 cleans 145 lbs',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Navy Chief Special Warfare Operator (SEAL) Adam Lee Brown',
  },
  {
    // 35
    name: 'Coe',
    sub: '10 rounds for time',
    desc1: '10 thrusters 95 lbs',
    desc2: '10 ring push ups',
    desc3: '',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Sgt. Keith Adam Coe',
  },
  {
    // 36
    name: 'Severin',
    sub: 'with 20 lb vest for time',
    desc1: '50 strict pull ups',
    desc2: '100 hand-release push ups',
    desc3: '5km run',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Sgt. 1st Class Severin W. Summers III',
  },
  {
    // 37
    name: 'Helton',
    sub: '3 rounds for time',
    desc1: '800m run',
    desc2: '30 DB squat cleans 50 lbs',
    desc3: '30 burpees',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Air Force Security Forces 1st Lt. Joseph D. Helton',
  },
  {
    // 38
    name: 'Jack',
    sub: '20 min amrap',
    desc1: '10 push presses 115 lbs',
    desc2: '10 KB swings 1.5 poods',
    desc3: '10 box jumps 24"',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Staff Sgt. Jack M. Martin III',
  },
  {
    // 39
    name: 'Forrest',
    sub: '3 rounds for time',
    desc1: '20 L pull ups',
    desc2: '30 T2B',
    desc3: '40 burpees',
    desc4: '800m run',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Drug Enforcement Administration Special Agent Forrest Nelson Leamon',
  },
  {
    // 40
    name: 'Bulger',
    sub: '10 rounds for time',
    desc1: '150m run',
    desc2: '7 C2B pull ups',
    desc3: '7 front squats 135 lbs',
    desc4: '7 handstand push ups',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Canadian Forces Cpl. Nicholas Bulger',
  },
  {
    // 41
    name: 'Brenton',
    sub: '5 rounds for time',
    desc1: '100 ft bear crawl',
    desc2: '100 ft standing broad jump',
    desc3: '5 burpees after every 5 broad jumps',
    desc4: 'wear a 20 lb vest if you have one',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Field Training Officer Timothy Quinn Brenton',
  },
  {
    // 42
    name: 'Blake',
    sub: '4 rounds for time',
    desc1: '100 ft walking lunge with 45 lb plate OH',
    desc2: '30 box jumps 24"',
    desc3: '20 wall ball shots 20 lbs',
    desc4: '10 handstand push ups',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Navy Senior Chief Cryptologic Technician David Blake McLendon',
  },
  {
    // 43
    name: 'Collin',
    sub: '6 rounds for time',
    desc1: '400m sandbag carry 50 lbs',
    desc2: '12 push presses 115 lbs',
    desc3: '12 box jumps 24"',
    desc4: '12 sumo DLs high pull 95 lbs',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Navy Special Warfare Operator Chief Collin Trent Thomas',
  },
  {
    // 44
    name: 'Thompson',
    sub: '10 rounds for time',
    desc1: '1 rope climb 15 ft',
    desc2: '29 back squat 95 lbs',
    desc3: '10m barbell farmer carry 135 lbs',
    desc4: 'begin rope climbs seated on the floor',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Capt. David J. Thompson',
  },
  {
    // 45
    name: 'Whitten',
    sub: '5 rounds for time',
    desc1: '22 KB swings 2 poods',
    desc2: '22 box jumps 24"',
    desc3: '400m run',
    desc4: '22 burpees',
    desc5: '22 wall ball shots 20 lbs',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Capt. Dan Whitten',
  },
  {
    // 46
    name: 'Bull',
    sub: '2 rounds for time',
    desc1: '200 double unders ',
    desc2: '50 OH squats 135 lbs',
    desc3: '50 pull ups',
    desc4: '1 mile run',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Marine Corps Capt. Brandon “Bull” Barrett',
  },
  {
    // 47
    name: 'Rankel',
    sub: '20 min amrap',
    desc1: '6 DLs 225 lbs',
    desc2: '7 burpee pull ups',
    desc3: '10 KB swings 2 poods',
    desc4: '200m run',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Marine Corps Sgt. John Rankel',
  },
  {
    // 48
    name: 'Holbrook',
    sub: '10 rounds for time',
    desc1: '5 thrusters 115 lbs',
    desc2: '10 pull ups',
    desc3: '100m sprint',
    desc4: '1 min rest',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Capt. Jason Holbrook',
  },
  {
    // 49
    name: 'Ledesma',
    sub: '20 min amrap',
    desc1: '5 parallette handstand push ups',
    desc2: '10 toes to rings',
    desc3: '15 medicine ball cleans 20 lbs',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'Narcotics Detective and Special Assignment Unit Operator Carlos Ledesma',
  },
  {
    // 50
    name: 'Wittman',
    sub: '7 rounds for time',
    desc1: '15 KB swings 1.5 poods',
    desc2: '15 power cleans 95 lbs',
    desc3: '15 box jumps 24"',
    desc4: '',
    desc5: '',
    desc6: '',
    desc7: '',
    desc8: '',
    desc9: '',
    desc10: '',
    desc11: '',
    desc12: '',
    desc13: '',
    desc14: '',
    desc15: '',
    desc16: '',
    desc17: '',
    desc18: '',
    desc19: '',
    desc20: '',
    hero: 'U.S. Army Sgt. Jeremiah Wittman',
  },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
  // {
  //   //
  //   name: '',
  //   sub: '',
  //   desc1: '',
  //   desc2: '',
  //   desc3: '',
  //   desc4: '',
  //   desc5: '',
  //   desc6: '',
  //   desc7: '',
  //   desc8: '',
  //   desc9: '',
  //   desc10: '',
  //   desc11: '',
  //   desc12: '',
  //   desc13: '',
  //   desc14: '',
  //   desc15: '',
  //   desc16: '',
  //   desc17: '',
  //   desc18: '',
  //   desc19: '',
  //   desc20: '',
  //   hero: '',
  // },
]
